posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='post_index'),
    url(r'^/create/$', views.create, name='create'),
]

testsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', RedirectView.as_view(url='posts', permanent=False), name='index')
]

posts/models.py
from __future__ import unicode_literals

from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

posts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Post
from .forms import PostForm


def index(request):
    return render(request, 'posts/index.html', {'posts': Post.objects.all()})


def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, instance=Post())
        if form.is_valid():
            form.save()
            # @TODO add route name
            return HttpResponseRedirect('/posts/')
    else:
        form = PostForm(instance=Post())

    return render(request, 'posts/create.html', {'form': form})

posts/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Django</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'posts:create' %}">New post</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>

</body>
</html>

posts/templates/posts/create.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'posts:create'  %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" class="btn btn-success" />
    </form>
{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %}

{% block content %}
<ul>
    {% for post in posts %}
    <li>
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}